title: ESIIL workshop GitHub Unit 1 'Spruce up your website'
description: Check out my projects!
logo: https://media.licdn.com/dms/image/C560BAQFq0YSsv0NJkg/company-logo_200_200/0/1660000892248?e=2147483647&v=beta&t=4Jvtup-z3wU7onKkqBg-ehU_ZTLsX7krMtleYw1WMRo
remote_theme: pages-themes/time-machine@v0.2.0
